const item = (category, id, name, rarity, visual, renderSpec) => Object.freeze({
  id, category, name, rarity, price:null, asset:null, visual,
  implKey:`${category}:${id}`,
  testOnly:true, purchasable:false, persistable:false,
  renderSpec:Object.freeze(renderSpec),
});

export const LINE_STYLE_ITEMS_V11 = Object.freeze([
  item('line_style','ls11_u_champion_stitch','챔피언 실밥선','uncommon','야구공 실밥처럼 좌우로 교차하는 매듭선. 선택 색상 적용',{fx:'ls11_u_champion_stitch',width:2.4,tension:.12,color:'#f5f7fa',colorMode:'custom',motionTier:'gentle'}),
  item('line_style','ls11_u_ink_tactics','묵향 병법선','uncommon','먹의 농담·갈필·섬유 끝이 살아 있는 마른 붓선. 선택 색상 적용',{fx:'ls11_u_ink_tactics',width:2.6,tension:.08,color:'#d6e0e8',colorMode:'custom',motionTier:'gentle'}),
  item('line_style','ls12_u_pace_tape','러너의 페이스 테이프','uncommon','접힌 구간과 무광 면이 교차하는 러닝 페이스 테이프. 선택 색상 적용',{fx:'ls12_u_pace_tape',width:2.6,tension:.06,color:'#f5f7fa',colorMode:'custom',motionTier:'gentle'}),
  item('line_style','ls12_u_measure_cable','톱니 측정 케이블','uncommon','금속 커플러와 눈금 슬리브가 체결된 측정 케이블. 선택 색상 적용',{fx:'ls12_u_measure_cable',width:2.6,tension:.1,color:'#f5f7fa',colorMode:'custom',motionTier:'gentle'}),
  item('line_style','ls12_u_dawn_reflector','새벽 러닝 궤적','uncommon','반사 테이프 조각에 새벽빛이 천천히 훑는 러닝선. 선택 색상 적용',{fx:'ls12_u_dawn_reflector',width:2.5,tension:.12,color:'#f5f7fa',colorMode:'custom',motionTier:'gentle'}),
  item('line_style','ls11_r_wolong_feather','와룡의 백우선','rare','중앙 깃대와 비대칭 깃결이 포개지는 백우선 궤적. 선택 색상 적용',{fx:'ls11_r_wolong_feather',width:2.7,tension:.16,color:'#8ce8df',colorMode:'custom',motionTier:'subtle'}),
  item('line_style','ls11_r_red_cliff_fire','적벽의 화공선','rare','탄화된 먹선 안에서 붉은 불씨가 간헐적으로 살아나는 화공 궤적',{fx:'ls11_r_red_cliff_fire',width:2.8,tension:.12,color:'#ff7a3d',colorMode:'fixed',motionTier:'subtle'}),
  item('line_style','ls12_r_moon_bronze','월광 청동각인','rare','산화 청동 홈과 황동 리벳을 정교하게 새긴 고대 측량선',{fx:'ls12_r_moon_bronze',width:2.8,tension:.1,color:'#65d6c7',colorMode:'fixed',motionTier:'subtle'}),
  item('line_style','ls12_r_glasshouse_vein','유리온실의 잎맥','rare','투명한 줄기에서 잎맥과 이슬이 번갈아 자라는 생장선. 선택 색상 적용',{fx:'ls12_r_glasshouse_vein',width:2.7,tension:.18,color:'#7fe6a2',colorMode:'custom',motionTier:'subtle'}),
  item('line_style','ls12_r_constellation_chart','별자리 항해도','rare','행성·별·항법 눈금이 서로 다른 간격으로 이어지는 천문 항해선. 선택 색상 적용',{fx:'ls12_r_constellation_chart',width:2.6,tension:.12,color:'#a8d8ff',colorMode:'custom',motionTier:'subtle'}),
  item('line_style','ls11_e_thunder_current','천둥왕자의 전류선','epic','청백 전류와 황금 낙뢰가 서로 다른 속도로 질주하는 영웅 연출',{fx:'ls11_e_thunder_current',width:2.9,tension:.12,color:'#9ddcff',colorMode:'fixed',motionTier:'heroic'}),
  item('line_style','ls12_e_spider_tension','거미차원의 장력선','epic','적청 차원실과 거미줄 장력 마디가 수축·이완하는 영웅 연출',{fx:'ls12_e_spider_tension',width:2.9,tension:.16,color:'#75baff',colorMode:'fixed',motionTier:'heroic'}),
  item('line_style','ls11_e_crimson_chaos','진홍 마녀의 확률선','epic','확률 분기와 진홍 룬 파편이 갈라졌다 재결합하는 영웅 연출',{fx:'ls11_e_crimson_chaos',width:2.9,tension:.18,color:'#ff477e',colorMode:'fixed',motionTier:'heroic'}),
  item('line_style','ls12_e_starforged_nano','별벼림 나노회로','epic','금속 장갑판과 나노 입자·반응로 펄스가 조립되는 영웅 연출',{fx:'ls12_e_starforged_nano',width:3,tension:.1,color:'#ffb347',colorMode:'fixed',motionTier:'heroic'}),
  item('line_style','ls12_e_arcane_seam','비전 차원봉합선','epic','비전 고리와 봉합 스티치가 공간 균열을 연속해서 닫는 영웅 연출',{fx:'ls12_e_arcane_seam',width:2.9,tension:.16,color:'#b996ff',colorMode:'fixed',motionTier:'heroic'}),
  item('line_style','ls11_m_frozen_runeblade','얼어붙은 왕의 영혼수확','mythic','서리 폭풍·파멸 지대·영혼 수확이 단계적으로 폭발하는 신화 연출',{fx:'ls11_m_frozen_runeblade',width:3.2,tension:.14,color:'#bdefff',colorMode:'fixed',motionTier:'mythic'}),
  item('line_style','ls11_m_nether_twinblade','배신자의 안광 궤적','mythic','쌍월도 궤적·안광·지옥불이 교차하며 악마 형상으로 점화되는 신화 연출',{fx:'ls11_m_nether_twinblade',width:3.2,tension:.16,color:'#8cff68',colorMode:'fixed',motionTier:'mythic'}),
  item('line_style','ls12_m_domination_chain','밴시 여왕의 지배사슬','mythic','지배의 사슬과 통곡의 화살·밴시 잔영이 연속 전개되는 신화 연출',{fx:'ls12_m_domination_chain',width:3.2,tension:.15,color:'#d7c2ff',colorMode:'fixed',motionTier:'mythic'}),
  item('line_style','ls12_m_corrupted_ironstar','대족장의 타락한 강철별','mythic','강철별 충격과 타락한 소용돌이·모독의 균열이 충돌하는 신화 연출',{fx:'ls12_m_corrupted_ironstar',width:3.3,tension:.1,color:'#ff6a32',colorMode:'fixed',motionTier:'mythic'}),
  item('line_style','ls12_m_flamewreath_paradox','메디브의 화염고리 역설','mythic','화염 고리·냉기 구속·비전 탄막이 시간 역행과 함께 순환하는 신화 연출',{fx:'ls12_m_flamewreath_paradox',width:3.2,tension:.17,color:'#d8a8ff',colorMode:'fixed',motionTier:'mythic'}),
  item('line_style','ls12_m_tidal_archmage_frost','대제독의 빙결해일','mythic','청백색 비전 냉기가 물결처럼 흐르고 변곡점마다 눈꽃 결정이 피어나는 신화 연출',{fx:'ls12_m_tidal_archmage_frost',width:3.15,tension:.2,color:'#8fe9ff',colorMode:'fixed',motionTier:'mythic'}),
].sort((a,b)=>({uncommon:0,rare:1,epic:2,mythic:3}[a.rarity]-({uncommon:0,rare:1,epic:2,mythic:3}[b.rarity]))));

export const AMBIENT_EFFECT_ITEMS_V11 = Object.freeze([
  item('ambient_effect','ae11_u_navy_bear_victory','남색 곰의 승리비','uncommon','남색 응원 리본과 은빛 실밥, 구장 조명이 살랑이는 승리 연출',{fx:'ae11_u_navy_bear_victory',motionTier:'gentle'}),
  item('ambient_effect','ae11_u_twin_night_game','쌍별 야간경기','uncommon','쌍별 잔광과 적백 리본이 밤 구장을 천천히 가르는 연출',{fx:'ae11_u_twin_night_game',motionTier:'gentle'}),
  item('ambient_effect','ae11_u_tiger_homerun','호랑이의 홈런 불꽃','uncommon','호랑이 발톱 불씨와 홈런 축포가 가장자리를 밝히는 연출',{fx:'ae11_u_tiger_homerun',motionTier:'gentle'}),
  item('ambient_effect','ae11_r_crescent_dragon','월아청룡의 행진','rare','월아의 잔광과 청룡 비늘 바람이 유영하는 희귀 연출',{fx:'ae11_r_crescent_dragon',motionTier:'subtle'}),
  item('ambient_effect','ae11_r_imperial_jade_seal','황실 옥새의 금진','rare','옥새와 황금 운문이 느리게 맥동하는 황실 진법 연출',{fx:'ae11_r_imperial_jade_seal',motionTier:'subtle'}),
  item('ambient_effect','ae11_r_moon_archive','월하 서고의 지령','rare','달빛 문서와 먹구름, 청색 반딧불이 흐르는 서고 연출',{fx:'ae11_r_moon_archive',motionTier:'subtle'}),
  item('ambient_effect','ae11_e_starforged_reactor','별벼림 반응로','epic','적금 장갑 잔광과 반응로 파동이 전개되는 영웅 연출',{fx:'ae11_e_starforged_reactor',motionTier:'heroic'}),
  item('ambient_effect','ae11_e_spider_rift','거미차원의 균열','epic','거미줄 차원문과 적청 도시 잔광이 교차하는 영웅 연출',{fx:'ae11_e_spider_rift',motionTier:'heroic'}),
  item('ambient_effect','ae11_e_vibranium_guard','흑진동 수호장','epic','보랏빛 운동에너지와 흑금속 파편이 폭발하는 영웅 연출',{fx:'ae11_e_vibranium_guard',motionTier:'heroic'}),
  item('ambient_effect','ae11_m_banshee_dirge','밴시 여왕의 장송곡','mythic','혼령 비단과 검은 깃털, 진홍 화살비가 겹치는 신화 연출',{fx:'ae11_m_banshee_dirge',motionTier:'mythic'}),
  item('ambient_effect','ae11_m_iron_warchief','강철 대족장의 전쟁터','mythic','강철 사슬과 용암 도끼, 전장의 충격파가 휘몰아치는 신화 연출',{fx:'ae11_m_iron_warchief',motionTier:'mythic'}),
  item('ambient_effect','ae11_m_raven_arcane','까마귀탑의 비전폭풍','mythic','까마귀 군무와 비전 번개, 시간 파동이 중첩되는 신화 연출',{fx:'ae11_m_raven_arcane',motionTier:'mythic'}),
  item('ambient_effect','ae11_u_champion_stadium','챔피언의 구장','uncommon','구장 조명과 먼지가 외곽에서 잔잔하게 호흡하는 공간 연출',{fx:'ae11_u_champion_stadium',motionTier:'gentle'}),
  item('ambient_effect','ae11_u_ink_battlefield','먹빛 전장','uncommon','먹 번짐과 군기 그림자가 가장자리에서 살랑이는 공간 연출',{fx:'ae11_u_ink_battlefield',motionTier:'gentle'}),
  item('ambient_effect','ae11_r_eight_formation','팔진도의 바람','rare','청옥 진형과 깃털 흔적이 아주 느리게 호흡하는 저동적 공간 연출',{fx:'ae11_r_eight_formation',motionTier:'subtle'}),
  item('ambient_effect','ae11_r_red_cliff','적벽의 화공','rare','화선과 재가 간헐적으로만 반응하는 저동적 적벽 공간 연출',{fx:'ae11_r_red_cliff',motionTier:'subtle'}),
  item('ambient_effect','ae11_e_storm_dimension','폭풍 차원','epic','폭우·예고광·낙뢰·잔류 전류가 단계적으로 발생하는 영웅 연출',{fx:'ae11_e_storm_dimension',motionTier:'heroic'}),
  item('ambient_effect','ae11_e_crimson_chaos','진홍 혼돈장','epic','혼돈 리본·마법진·수정 파편이 다층 흐름장을 이루는 영웅 연출',{fx:'ae11_e_crimson_chaos',motionTier:'heroic'}),
  item('ambient_effect','ae11_m_frozen_crown','얼음왕관 눈보라','mythic','전후경 눈보라·냉기 안개·룬진·영혼불이 연속 전개되는 신화 연출',{fx:'ae11_m_frozen_crown',motionTier:'mythic'}),
  item('ambient_effect','ae11_m_black_sanctuary','검은 성소의 균열','mythic','황천 균열·지옥 유성·에너지 파도·흑요 파편이 폭발하는 신화 연출',{fx:'ae11_m_black_sanctuary',motionTier:'mythic'}),
  item('ambient_effect','ae12_m_tidal_archmage_blizzard','대제독의 비전 눈보라','mythic','육각 눈꽃과 얼음 결정, 청백색 비전 바람과 냉기 안개가 층층이 휘몰아치는 신화 연출',{fx:'ae12_m_tidal_archmage_blizzard',motionTier:'mythic'}),
].sort((a,b)=>({uncommon:0,rare:1,epic:2,mythic:3}[a.rarity]-({uncommon:0,rare:1,epic:2,mythic:3}[b.rarity]))));
