import { getUser,getWorkoutSessions,saveWorkoutSession,deleteWorkoutSession,getWorkoutProfile,saveWorkoutProfile,getInbodyRecords,saveInbodyRecord } from './db.js';
import { activityDay } from './daily-rewards.js';
import { EXERCISE_CATALOG,kgToLb,lbToKg } from './workout-catalog.js';
import { esc } from './util.js';
import { isAuthed } from './auth.js';

const uid=new URLSearchParams(location.search).get('user')||localStorage.getItem('uid');
if(!uid)location.href='index.html';
const $=id=>document.getElementById(id);
let user,profile,sessions=[],range='7',draft=null,kind='strength',intensity=null,draftTimer=null;
const DRAFT_KEY=`mweg_workout_draft_${uid}`;
const emptyDraft=()=>({day:new URLSearchParams(location.search).get('date')||activityDay(),kind:'strength',startedAt:new Date().toISOString(),gymId:profile?.lastGymId||null,exercises:[],running:{distanceKm:'',durationSec:0,cadence:'',environment:'outdoor'},note:'',perceivedIntensity:null});
function toast(text,type='ok'){const el=$('toast');el.textContent=text;el.className=`toast show ${type}`;setTimeout(()=>el.className='toast',1800)}
function fmtDuration(sec){const n=Number(sec)||0;return `${Math.floor(n/3600)}:${String(Math.floor(n%3600/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function parseDuration(v){const p=String(v||'').split(':').map(Number);return p.length===3?p[0]*3600+p[1]*60+p[2]:p.length===2?p[0]*3600+p[1]*60:0}
function dayAge(day){return Math.round((new Date(`${activityDay()}T12:00:00`)-new Date(`${day}T12:00:00`))/86400000)}
function selectedSessions(){return sessions.filter(s=>range==='all'||(dayAge(s.day)>=0&&dayAge(s.day)<Number(range)))}
function nav(){const links=[['input','✏️','데이터 입력','input.html'],['dashboard','⚖️','체중 그래프','dashboard.html'],['workout','🏋️','운동 그래프','workout.html'],['compare','👥','그래프 모아보기','compare.html'],['achievements','🏆','업적','achievements.html'],['dressroom','✨','쇼룸','dressroom.html']];$('bottomNav').innerHTML=links.map(([id,icon,label,file])=>`<a href="${file}?user=${encodeURIComponent(uid)}" class="${id==='workout'?'active':''}"><span class="icon">${icon}</span>${label}</a>`).join('')}
function sessionSets(s){return (s.exercises||[]).reduce((n,e)=>n+(e.sets||[]).filter(x=>x.completed!==false).length,0)}
function sessionVolume(s){return (s.exercises||[]).flatMap(e=>(e.sets||[])).reduce((n,x)=>n+(Number(x.kg)||0)*(Number(x.reps)||0),0)}
function muscleScores(rows){const scores={};rows.forEach(s=>(s.exercises||[]).forEach(e=>{const sets=(e.sets||[]).filter(x=>x.completed!==false).length;(e.primaryMuscles||[]).forEach(m=>scores[m]=(scores[m]||0)+sets);(e.secondaryMuscles||[]).forEach(m=>scores[m]=(scores[m]||0)+sets*.35)}));return Object.entries(scores).sort((a,b)=>b[1]-a[1])}
function render(){const rows=selectedSessions();const strength=rows.filter(s=>s.kind==='strength'),running=rows.filter(s=>s.kind==='running');const sets=strength.reduce((n,s)=>n+sessionSets(s),0),volume=strength.reduce((n,s)=>n+sessionVolume(s),0),distance=running.reduce((n,s)=>n+(Number(s.running?.distanceKm)||0),0);const muscles=muscleScores(rows),max=muscles[0]?.[1]||1;$('workoutContent').innerHTML=`<div class="wo-summary"><div class="wo-stat"><b>${rows.length}</b><span>운동 기록</span></div><div class="wo-stat"><b>${sets}</b><span>완료 세트</span></div><div class="wo-stat"><b>${Math.round(volume).toLocaleString()}kg</b><span>기록 볼륨</span></div><div class="wo-stat"><b>${distance.toFixed(1)}km</b><span>러닝 거리</span></div></div><div class="wo-grid" style="margin-top:12px"><section class="wo-card"><h2>부위별 운동량</h2>${muscles.length?`<div class="muscle-list">${muscles.map(([m,v])=>`<div class="muscle-row"><span>${esc(m)}</span><div class="muscle-track"><i style="width:${Math.max(5,v/max*100)}%"></i></div><b>${v%1?v.toFixed(1):v}</b></div>`).join('')}</div><p style="font-size:9px;color:var(--muted);margin-top:10px">주동근 100% · 보조근 35%로 배분한 기록 기반 지표입니다.</p>`:`<div class="wo-empty">아직 운동 기록이 없습니다.<br>한 세트부터 기록해보세요.</div>`}</section><section class="wo-card"><h2>운동 기록</h2><div class="session-list">${rows.slice().reverse().map(sessionHTML).join('')||'<div class="wo-empty">기록이 쌓이면 이곳에서 바로 확인할 수 있습니다.</div>'}</div></section></div>`;document.querySelectorAll('[data-edit-session]').forEach(b=>b.onclick=()=>{const found=sessions.find(s=>s.id===b.dataset.editSession);if(!found)return;localStorage.setItem(DRAFT_KEY,JSON.stringify(found));openWorkout()});document.querySelectorAll('[data-delete-session]').forEach(b=>b.onclick=async()=>{if(!confirm('이 운동 기록을 삭제할까요?'))return;await deleteWorkoutSession(uid,b.dataset.deleteSession,b.dataset.day);sessions=sessions.filter(s=>s.id!==b.dataset.deleteSession);render();toast('운동 기록을 삭제했습니다.')})}
function sessionHTML(s){const actions=`<span><button class="session-delete" style="color:var(--teal)" data-edit-session="${s.id}">수정</button><button class="session-delete" data-delete-session="${s.id}" data-day="${s.day}">삭제</button></span>`;if(s.kind==='running'){const sec=Number(s.running?.durationSec)||0,km=Number(s.running?.distanceKm)||0,pace=km?Math.round(sec/km):0;return `<article class="session-item"><span class="session-icon">🏃</span><div><b>${s.day} · 러닝 ${km.toFixed(2)}km</b><small>${fmtDuration(sec)}${pace?` · ${Math.floor(pace/60)}'${String(pace%60).padStart(2,'0')}\"/km`:''}${s.running?.cadence?` · ${s.running.cadence}spm`:''}</small></div>${actions}</article>`}return `<article class="session-item"><span class="session-icon">🏋️</span><div><b>${s.day} · ${(s.exercises||[]).length}개 운동</b><small>${sessionSets(s)}세트 · ${Math.round(sessionVolume(s)).toLocaleString()}kg 볼륨${s.status==='draft'?' · 임시저장':''}</small></div>${actions}</article>`}
function gyms(){return [{id:'home',name:'홈트·장소 없음'},...(profile?.gyms||[])]}
function gymOptions(){return gyms().map(g=>`<option value="${esc(g.id)}" ${draft?.gymId===g.id?'selected':''}>${esc(g.name)}</option>`).join('')+`<option value="__add">+ 헬스장 추가</option>`}
function openWorkout(){try{draft=JSON.parse(localStorage.getItem(DRAFT_KEY))||emptyDraft()}catch{draft=emptyDraft()}draft.day=draft.day||activityDay();kind=draft.kind||'strength';intensity=draft.perceivedIntensity||null;$('sessionDay').value=draft.day;$('startTime').value=new Date(draft.startedAt||Date.now()).toTimeString().slice(0,5);$('gymSelect').innerHTML=gymOptions();$('sessionNote').value=draft.note||'';$('runDistance').value=draft.running?.distanceKm||'';$('runDuration').value=draft.running?.durationSec?fmtDuration(draft.running.durationSec):'';$('runCadence').value=draft.running?.cadence||'';$('runEnvironment').value=draft.running?.environment||'outdoor';setKind(kind);renderPicker();renderBlocks();renderIntensity();calcPace();$('workoutModal').hidden=false}
function closeWorkout(){$('workoutModal').hidden=true}
function setKind(next){kind=next;draft.kind=next;document.querySelectorAll('[data-kind]').forEach(b=>b.classList.toggle('active',b.dataset.kind===next));$('strengthEditor').hidden=next!=='strength';$('runningEditor').hidden=next!=='running';scheduleDraft()}
function renderPicker(q=''){const needle=q.trim().toLowerCase();$('exercisePicker').innerHTML=EXERCISE_CATALOG.filter(x=>x.id!=='custom'&&(!needle||`${x.name} ${x.equipment} ${x.primary.join(' ')}`.toLowerCase().includes(needle))).map(x=>`<button type="button" data-add-exercise="${x.id}"><b>${esc(x.name)}</b><small style="display:block;color:var(--muted);margin-top:2px">${esc(x.equipment)} · ${esc(x.primary.join(' · '))}</small></button>`).join('');document.querySelectorAll('[data-add-exercise]').forEach(b=>b.onclick=()=>addExercise(b.dataset.addExercise))}
function addExercise(id){const c=EXERCISE_CATALOG.find(x=>x.id===id);draft.exercises.push({id:crypto.randomUUID(),catalogId:c.id,name:c.name,equipment:c.equipment,format:c.format,primaryMuscles:c.primary,secondaryMuscles:c.secondary,sets:[newSet()]});renderBlocks();scheduleDraft()}
function newSet(prev={}){return {id:crypto.randomUUID(),originalWeight:prev.originalWeight||0,inputUnit:prev.inputUnit||'kg',reps:prev.reps||0,durationSec:prev.durationSec||0,completed:true,note:''}}
function renderBlocks(){$('exerciseBlocks').innerHTML=(draft.exercises||[]).map((e,ei)=>`<article class="exercise-block"><div class="exercise-head"><div><b>${esc(e.name)}</b><small>${esc((e.primaryMuscles||[]).join(' · '))} · ${esc(e.equipment||'')}</small></div><button type="button" class="session-delete" data-rm-ex="${ei}">삭제</button></div><div>${(e.sets||[]).map((s,si)=>setHTML(e,ei,s,si)).join('')}</div><button type="button" class="set-add" data-add-set="${ei}">+ 직전 세트 복사</button></article>`).join('');document.querySelectorAll('[data-rm-ex]').forEach(b=>b.onclick=()=>{draft.exercises.splice(+b.dataset.rmEx,1);renderBlocks();scheduleDraft()});document.querySelectorAll('[data-add-set]').forEach(b=>{b.onclick=()=>{const e=draft.exercises[+b.dataset.addSet];e.sets.push(newSet(e.sets.at(-1)));renderBlocks();scheduleDraft()}});document.querySelectorAll('[data-set-field]').forEach(el=>el.oninput=()=>updateSet(el));document.querySelectorAll('[data-rm-set]').forEach(b=>b.onclick=()=>{draft.exercises[+b.dataset.ei].sets.splice(+b.dataset.si,1);renderBlocks();scheduleDraft()})}
function setHTML(e,ei,s,si){const body=e.format==='duration';return `<div class="set-row"><span class="set-unit">${si+1}</span>${body?`<input type="number" min="0" value="${s.durationSec||''}" placeholder="초" data-set-field="durationSec" data-ei="${ei}" data-si="${si}">`:`<input type="number" min="0" step="0.1" value="${s.originalWeight||''}" placeholder="무게" data-set-field="originalWeight" data-ei="${ei}" data-si="${si}">`}<select data-set-field="inputUnit" data-ei="${ei}" data-si="${si}" ${body?'disabled':''}><option value="kg" ${s.inputUnit!=='lb'?'selected':''}>kg</option><option value="lb" ${s.inputUnit==='lb'?'selected':''}>lb</option></select>${body?`<span class="set-unit">시간</span>`:`<input type="number" min="0" value="${s.reps||''}" placeholder="횟수" data-set-field="reps" data-ei="${ei}" data-si="${si}">`}<button type="button" class="set-remove" data-rm-set data-ei="${ei}" data-si="${si}">×</button></div>${body?'':`<div class="set-unit" style="text-align:left;margin:2px 0 0 34px">${s.inputUnit==='lb'?`${lbToKg(s.originalWeight)}kg`:`${kgToLb(s.originalWeight)}lb`} · 바벨/스미스는 봉·시작 중량 제외</div>`}`}
function updateSet(el){const s=draft.exercises[+el.dataset.ei].sets[+el.dataset.si];s[el.dataset.setField]=el.dataset.setField==='inputUnit'?el.value:Number(el.value)||0;if(el.dataset.setField==='inputUnit')renderBlocks();scheduleDraft()}
function scheduleDraft(){clearTimeout(draftTimer);$('draftState').textContent='변경사항 저장 중…';draftTimer=setTimeout(()=>{syncForm();localStorage.setItem(DRAFT_KEY,JSON.stringify(draft));$('draftState').textContent='임시저장됨'},350)}
function syncForm(){draft.day=$('sessionDay').value||activityDay();draft.gymId=$('gymSelect').value||null;draft.note=$('sessionNote').value;draft.perceivedIntensity=intensity;draft.running={distanceKm:Number($('runDistance').value)||0,durationSec:parseDuration($('runDuration').value),cadence:$('runCadence').value===''?null:Number($('runCadence').value),environment:$('runEnvironment').value}}
function renderIntensity(){document.querySelectorAll('#intensity button').forEach(b=>b.classList.toggle('active',+b.dataset.v===+intensity))}
function calcPace(){const km=Number($('runDistance').value)||0,sec=parseDuration($('runDuration').value);$('runPace').value=km&&sec?`${Math.floor(sec/km/60)}'${String(Math.round(sec/km)%60).padStart(2,'0')}\"/km`:''}
async function addGym(){const name=prompt('헬스장 이름을 입력하세요.');if(!name){$('gymSelect').value=draft.gymId||'home';return}const gym={id:crypto.randomUUID(),name:name.trim().slice(0,40)};profile.gyms=[...(profile.gyms||[]),gym];profile.lastGymId=gym.id;await saveWorkoutProfile(uid,profile);draft.gymId=gym.id;$('gymSelect').innerHTML=gymOptions();toast('헬스장을 저장했습니다.')}
async function save(status){syncForm();draft.status=status;draft.completedAt=status==='complete'?new Date().toISOString():null;const saved=await saveWorkoutSession(uid,draft);sessions=sessions.filter(s=>s.id!==saved.id).concat(saved);profile.lastGymId=draft.gymId;await saveWorkoutProfile(uid,profile);localStorage.removeItem(DRAFT_KEY);closeWorkout();render();toast(status==='complete'?'운동 기록을 완료했습니다.':'임시저장했습니다.')}
async function openInbody(){const rows=await getInbodyRecords(uid);$('ibDate').value=activityDay();$('inbodyHistory').innerHTML=rows.slice(-8).reverse().map(r=>`<div class="session-item"><span>📋</span><div><b>${r.date}</b><small>체중 ${r.weight??'-'}kg · 골격근량 ${r.skeletalMuscle??'-'}kg · 체지방률 ${r.bodyFatPercent??'-'}%</small></div></div>`).join('')||'<div class="wo-empty">저장된 인바디 기록이 없습니다.</div>';$('inbodyModal').hidden=false}
document.querySelectorAll('.wo-tabs button').forEach(b=>b.onclick=()=>{range=b.dataset.range;document.querySelectorAll('.wo-tabs button').forEach(x=>x.classList.toggle('active',x===b));render()});$('newWorkoutBtn').onclick=openWorkout;$('inbodyBtn').onclick=openInbody;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('.wo-modal').hidden=true);document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>setKind(b.dataset.kind));$('exerciseSearch').oninput=e=>renderPicker(e.target.value);$('gymSelect').onchange=e=>e.target.value==='__add'?addGym():scheduleDraft();['sessionDay','startTime','runDistance','runDuration','runCadence','runEnvironment','sessionNote'].forEach(id=>$(id).addEventListener('input',()=>{if(id.startsWith('run'))calcPace();scheduleDraft()}));$('noteToggle').onclick=()=>{$('noteWrap').hidden=!$('noteWrap').hidden};document.querySelectorAll('#intensity button').forEach(b=>b.onclick=()=>{intensity=+b.dataset.v===intensity?null:+b.dataset.v;renderIntensity();scheduleDraft()});$('saveDraftBtn').onclick=()=>save('draft').catch(e=>toast(e.message,'err'));$('workoutForm').onsubmit=e=>{e.preventDefault();save('complete').catch(err=>toast(err.message,'err'))};$('inbodyForm').onsubmit=async e=>{e.preventDefault();try{await saveInbodyRecord(uid,{date:$('ibDate').value,weight:$('ibWeight').value,skeletalMuscleMass:$('ibMuscle').value,bodyFatPercent:$('ibFat').value});toast('내 데이터를 저장했습니다.');openInbody()}catch(err){toast(err.message,'err')}};
(async()=>{nav();user=await getUser(uid);if(!user||user.passwordHash&&!isAuthed(uid,user.passwordHash)){location.href='index.html?select=1';return}[profile,sessions]=await Promise.all([getWorkoutProfile(uid),getWorkoutSessions(uid)]);render()})().catch(e=>{$('workoutContent').innerHTML=`<div class="wo-card wo-empty">불러오지 못했습니다.<br>${esc(e.message)}</div>`});
