export const MUSCLES = Object.freeze([
  '가슴 상부','가슴 중·하부','등 상부','광배근','허리','어깨 전면','어깨 측면','어깨 후면',
  '이두','삼두','전완','복근','둔근','대퇴사두','햄스트링','종아리','전신·심폐',
]);

const e=(id,name,equipment,primary,secondary=[],format='weight_reps',note='')=>Object.freeze({id,name,equipment,primary,secondary,format,note});

export const EXERCISE_CATALOG = Object.freeze([
  e('bench_press','벤치프레스','바벨',['가슴 중·하부'],['삼두','어깨 전면']),
  e('incline_bench','인클라인 벤치프레스','바벨',['가슴 상부'],['삼두','어깨 전면']),
  e('decline_bench','디클라인 벤치프레스','바벨',['가슴 중·하부'],['삼두']),
  e('dumbbell_press','덤벨 벤치프레스','덤벨',['가슴 중·하부'],['삼두','어깨 전면']),
  e('incline_db_press','인클라인 덤벨프레스','덤벨',['가슴 상부'],['삼두','어깨 전면']),
  e('chest_press','체스트 프레스','머신',['가슴 중·하부'],['삼두','어깨 전면']),
  e('incline_chest_press','인클라인 체스트 프레스','머신',['가슴 상부'],['삼두','어깨 전면']),
  e('pec_deck','펙덱 플라이','머신',['가슴 중·하부'],['어깨 전면']),
  e('cable_fly','케이블 플라이','케이블',['가슴 중·하부'],['어깨 전면']),
  e('push_up','푸시업','맨몸',['가슴 중·하부'],['삼두','어깨 전면'],'bodyweight_reps'),
  e('dip_chest','딥스 · 가슴','맨몸/어시스트',['가슴 중·하부'],['삼두'],'assisted_reps'),
  e('lat_pulldown','랫풀다운','케이블/머신',['광배근'],['이두','등 상부']),
  e('pull_up','풀업','맨몸/어시스트',['광배근'],['이두','등 상부'],'assisted_reps'),
  e('chin_up','친업','맨몸/어시스트',['광배근','이두'],['등 상부'],'assisted_reps'),
  e('barbell_row','바벨 로우','바벨',['등 상부','광배근'],['이두','허리']),
  e('dumbbell_row','원암 덤벨 로우','덤벨',['광배근'],['등 상부','이두']),
  e('seated_row','시티드 로우','케이블/머신',['등 상부','광배근'],['이두']),
  e('tbar_row','티바 로우','원판 머신',['등 상부'],['광배근','이두']),
  e('high_row','하이 로우','머신',['등 상부','광배근'],['이두']),
  e('pullover_machine','풀오버 머신','머신',['광배근'],['가슴 중·하부']),
  e('straight_arm_pulldown','스트레이트암 풀다운','케이블',['광배근'],['삼두']),
  e('back_extension','백 익스텐션','맨몸/원판',['허리'],['둔근','햄스트링'],'bodyweight_reps'),
  e('deadlift','데드리프트','바벨',['햄스트링','둔근','허리'],['등 상부','전완']),
  e('romanian_deadlift','루마니안 데드리프트','바벨/덤벨',['햄스트링','둔근'],['허리']),
  e('shoulder_press','숄더 프레스','덤벨/머신',['어깨 전면'],['어깨 측면','삼두']),
  e('overhead_press','오버헤드 프레스','바벨',['어깨 전면'],['어깨 측면','삼두']),
  e('lateral_raise','사이드 레터럴 레이즈','덤벨',['어깨 측면'],['어깨 전면']),
  e('cable_lateral_raise','케이블 레터럴 레이즈','케이블',['어깨 측면']),
  e('rear_delt_fly','리어 델트 플라이','머신/덤벨',['어깨 후면'],['등 상부']),
  e('face_pull','페이스 풀','케이블',['어깨 후면'],['등 상부']),
  e('front_raise','프론트 레이즈','덤벨/원판',['어깨 전면']),
  e('shrug','슈러그','바벨/덤벨',['등 상부'],['전완']),
  e('barbell_curl','바벨 컬','바벨',['이두'],['전완']),
  e('dumbbell_curl','덤벨 컬','덤벨',['이두'],['전완']),
  e('hammer_curl','해머 컬','덤벨',['이두','전완']),
  e('preacher_curl','프리처 컬','머신/바벨',['이두'],['전완']),
  e('cable_curl','케이블 컬','케이블',['이두'],['전완']),
  e('triceps_pushdown','트라이셉스 푸시다운','케이블',['삼두']),
  e('overhead_extension','오버헤드 트라이셉스 익스텐션','케이블/덤벨',['삼두']),
  e('skull_crusher','라잉 트라이셉스 익스텐션','바벨',['삼두']),
  e('close_grip_bench','클로즈그립 벤치프레스','바벨',['삼두'],['가슴 중·하부','어깨 전면']),
  e('dip_triceps','딥스 · 삼두','맨몸/어시스트',['삼두'],['가슴 중·하부'],'assisted_reps'),
  e('wrist_curl','리스트 컬','덤벨/바벨',['전완']),
  e('squat','백 스쿼트','바벨',['대퇴사두','둔근'],['햄스트링','허리']),
  e('front_squat','프론트 스쿼트','바벨',['대퇴사두'],['둔근','허리']),
  e('hack_squat','핵 스쿼트','원판 머신',['대퇴사두','둔근'],['햄스트링']),
  e('leg_press','레그 프레스','원판 머신',['대퇴사두','둔근'],['햄스트링']),
  e('leg_extension','레그 익스텐션','머신',['대퇴사두']),
  e('leg_curl','레그 컬','머신',['햄스트링']),
  e('bulgarian_split','불가리안 스플릿 스쿼트','덤벨/맨몸',['대퇴사두','둔근'],['햄스트링']),
  e('lunge','런지','덤벨/맨몸',['대퇴사두','둔근'],['햄스트링']),
  e('hip_thrust','힙 스러스트','바벨/머신',['둔근'],['햄스트링']),
  e('glute_kickback','글루트 킥백','케이블/머신',['둔근'],['햄스트링']),
  e('adductor','힙 어덕션','머신',['대퇴사두'],['둔근']),
  e('abductor','힙 어브덕션','머신',['둔근']),
  e('standing_calf','스탠딩 카프 레이즈','머신/맨몸',['종아리']),
  e('seated_calf','시티드 카프 레이즈','머신',['종아리']),
  e('crunch','크런치','맨몸',['복근'],'','bodyweight_reps'),
  e('cable_crunch','케이블 크런치','케이블',['복근']),
  e('leg_raise','레그 레이즈','맨몸',['복근'],'','bodyweight_reps'),
  e('ab_wheel','AB 슬라이드','맨몸',['복근'],['광배근','어깨 전면'],'bodyweight_reps'),
  e('plank','플랭크','맨몸',['복근'],['둔근'],'duration'),
  e('side_plank','사이드 플랭크','맨몸',['복근'],'','duration'),
  e('band_row','밴드 로우','밴드',['등 상부','광배근'],['이두'],'band_reps'),
  e('band_press','밴드 체스트 프레스','밴드',['가슴 중·하부'],['삼두'],'band_reps'),
  e('band_pull_apart','밴드 풀어파트','밴드',['어깨 후면','등 상부'],'','band_reps'),
  e('bodyweight_squat','맨몸 스쿼트','맨몸',['대퇴사두','둔근'],['햄스트링'],'bodyweight_reps'),
  e('burpee','버피','맨몸',['전신·심폐'],'','bodyweight_reps'),
  e('mountain_climber','마운틴 클라이머','맨몸',['복근','전신·심폐'],'','duration'),
  e('custom','사용자 운동','사용자 기구',['전신·심폐'],[]),
]);

export function catalogExercise(id){ return EXERCISE_CATALOG.find(item=>item.id===id) || EXERCISE_CATALOG.at(-1); }
export const kgToLb = kg => Math.round((Number(kg)||0) * 2.2046226218 * 100) / 100;
export const lbToKg = lb => Math.round((Number(lb)||0) * 0.45359237 * 100) / 100;

