const CACHE = 'weight-v134-fluid-two-column';
const ASSETS = [
  './index.html', './dashboard.html', './input.html', './import.html',
  './achievements.html', './compare.html', './dressroom.html', './shop.html', './guide.html', './visual-lab.html',
  './css/style.css', './css/showroom-card-themes.css',
  './js/firebase-config.js', './js/db.js', './js/auth.js',
  './js/chart-render.js', './js/achievements.js', './js/achievements-engine.js',
  './js/quests.js', './js/quest-panel.js', './js/showroom-fx.js', './js/showroom-fx-v11.js',
  './js/util.js', './js/daily-rewards.js', './js/meal-status.js', './js/showroom-v2.js',
  './js/today-message.js',
  './js/showroom-catalog-v2.js', './js/showroom-catalog-v4.generated.js', './js/showroom-graph-skins.js', './js/showroom-graph-skins-v12.js', './js/showroom-card-themes.js', './js/showroom-card-themes-v12.js', './js/showroom-profile-emojis-v6.js', './js/showroom-portrait-frames-v7.js', './js/showroom-point-markers-v9.js', './js/showroom-trophies-v10.js', './js/showroom-taxonomy.js', './js/showroom-fullsets-v13.js', './js/showroom-collection.js', './js/titles-catalog-v2.js', './js/achievement-item-rewards-v2.js',
  './manifest.json', './favicon.png',
  './register-sw.js',
  './assets/showroom-v4/graph_skin/gs4_uncommon_ironpeak_workshop.webp',
  './assets/showroom-v4/graph_skin/gs4_uncommon_moonlit_inn.webp',
  './assets/showroom-v4/graph_skin/gs4_uncommon_desert_caravan.webp',
  './assets/showroom-v4/graph_skin/gs4_rare_worldtree_dreamway.webp',
  './assets/showroom-v4/graph_skin/gs4_rare_storm_kingdom.webp',
  './assets/showroom-v4/graph_skin/gs4_rare_red_iron_fortress.webp',
  './assets/showroom-v4/graph_skin/gs4_epic_silvermoon_court.webp',
  './assets/showroom-v4/graph_skin/gs4_epic_starforged_creation.webp',
  './assets/showroom-v4/graph_skin/gs4_epic_deepsea_queen_palace.webp',
  './assets/showroom-v4/graph_skin/gs4_legendary_frozen_crown.webp',
  './assets/showroom-v4/graph_skin/gs4_legendary_nether_black_sanctum.webp',
  './assets/showroom-v4/graph_skin/gs4_legendary_dragonflame_nest.webp',
  './assets/showroom-v12/graph_skin/gs12_u_navy_bear_dugout.webp',
  './assets/showroom-v12/graph_skin/gs12_u_twin_night_stadium.webp',
  './assets/showroom-v12/graph_skin/gs12_u_tiger_bullpen.webp',
  './assets/showroom-v12/graph_skin/gs12_u_orange_eagle_skybox.webp',
  './assets/showroom-v12/graph_skin/gs12_u_dawn_riverside_track.webp',
  './assets/showroom-v12/graph_skin/gs12_r_wolong_formation.webp',
  './assets/showroom-v12/graph_skin/gs12_r_red_cliff_firefleet.webp',
  './assets/showroom-v12/graph_skin/gs12_r_crescent_dragon_shrine.webp',
  './assets/showroom-v12/graph_skin/gs12_r_silver_spear_pass.webp',
  './assets/showroom-v12/graph_skin/gs12_r_imperial_seal_archive.webp',
  './assets/showroom-v12/graph_skin/gs12_e_thunder_astral_bridge.webp',
  './assets/showroom-v12/graph_skin/gs12_e_crimson_reality_garden.webp',
  './assets/showroom-v12/graph_skin/gs12_e_spider_dimension_city.webp',
  './assets/showroom-v12/graph_skin/gs12_e_mirror_sanctum.webp',
  './assets/showroom-v12/graph_skin/gs12_e_vibranium_kingdom.webp',
  './assets/showroom-v12/graph_skin/gs12_m_banshee_black_wall.webp',
  './assets/showroom-v12/graph_skin/gs12_m_iron_warchief_siege.webp',
  './assets/showroom-v12/graph_skin/gs12_m_raven_time_corridor.webp',
  './assets/showroom-v12/graph_skin/gs12_m_tide_sage_fortress.webp',
  './assets/showroom-v12/graph_skin/gs12_m_moon_priestess_sanctuary.webp',
  './assets/showroom-v12/card_theme/ct12_r_rediron_warchief_hall.webp',
  './assets/showroom-v12/card_theme/ct12_e_starforged_observatory.webp',
  './assets/showroom-v12/card_theme/ct12_m_deepsea_coral_court.webp',
  './assets/showroom-v12/card_theme/ct12_m_storm_lion_hall.webp',
  './assets/showroom-v12/card_theme/ct12_m_iron_warchief_command.webp',
  './assets/showroom-v12/card_theme/ct12_m_tide_admiral_cabin.webp',
  './assets/showroom-v12/card_theme/ct12_m_moon_priestess_altar.webp',
  './assets/showroom-v12/card_theme/ct12_m_dragonfire_council.webp',
  './assets/showroom-v9/point_marker/pm_u_bears_signature_high.png',
  './assets/showroom-v9/point_marker/pm_u_bears_signature_low.png',
  './assets/showroom-v9/point_marker/pm_u_twins_signature_high.png',
  './assets/showroom-v9/point_marker/pm_u_twins_signature_low.png',
  './assets/showroom-v9/point_marker/pm_u_softbear_signature_high.png',
  './assets/showroom-v9/point_marker/pm_u_softbear_signature_low.png',
  './assets/showroom-v9/point_marker/pm_r_feather_stratagem_high.png',
  './assets/showroom-v9/point_marker/pm_r_feather_stratagem_low.png',
  './assets/showroom-v9/point_marker/pm_e_thunder_hammer_high.png',
  './assets/showroom-v9/point_marker/pm_e_thunder_hammer_low.png',
  './assets/showroom-v9/point_marker/pm_l_frozen_runeblade_high.png',
  './assets/showroom-v9/point_marker/pm_l_frozen_runeblade_low.png',
  './assets/showroom-v9/point_marker/pm_l_tidal_archmage_high.png',
  './assets/showroom-v9/point_marker/pm_l_tidal_archmage_low.png',
  './assets/showroom-v9/point_marker/pm_l_iron_warchief_high.png',
  './assets/showroom-v9/point_marker/pm_l_iron_warchief_low.png',
  './assets/showroom-v9/point_marker/pm_l_raven_tower_high.png',
  './assets/showroom-v9/point_marker/pm_l_raven_tower_low.png',
  './assets/showroom-v9/point_marker/pm_l_fel_twinblade_high.png',
  './assets/showroom-v9/point_marker/pm_l_fel_twinblade_low.png',
  './assets/showroom-v3/companion/cp_sleepy_golem.png',
  './assets/showroom-v3/companion/cp_candle_wisp.png',
  './assets/showroom-v3/companion/cp_satchel_mimic.png',
  './assets/showroom-v3/companion/cp_lantern_moth.png',
  './assets/showroom-v5/companion/cp_u01.png',
  './assets/showroom-v5/companion/cp_u02.png',
  './assets/showroom-v5/companion/cp_u03.png',
  './assets/showroom-v5/companion/cp_u04.png',
  './assets/showroom-v5/companion/cp_u05.png',
  './assets/showroom-v5/companion/cp_u06.png',
  './assets/showroom-v5/companion/cp_u07.png',
  './assets/showroom-v5/companion/cp_u08.png',
  './assets/showroom-v5/companion/cp_u09.png',
  './assets/showroom-v5/companion/cp_u10.png',
  './assets/showroom-v5/companion/cp_r01.png',
  './assets/showroom-v5/companion/cp_r02.png',
  './assets/showroom-v5/companion/cp_r03.png',
  './assets/showroom-v5/companion/cp_r04.png',
  './assets/showroom-v5/companion/cp_r05.png',
  './assets/showroom-v5/companion/cp_r06.png',
  './assets/showroom-v5/companion/cp_r07.png',
  './assets/showroom-v5/companion/cp_r08.png',
  './assets/showroom-v5/companion/cp_r09.png',
  './assets/showroom-v5/companion/cp_r10.png',
  './assets/showroom-v5/companion/cp_e01.png',
  './assets/showroom-v5/companion/cp_e02.png',
  './assets/showroom-v5/companion/cp_e03.png',
  './assets/showroom-v5/companion/cp_e04.png',
  './assets/showroom-v5/companion/cp_e05.png',
  './assets/showroom-v5/companion/cp_e06.png',
  './assets/showroom-v5/companion/cp_e07.png',
  './assets/showroom-v5/companion/cp_e08.png',
  './assets/showroom-v5/companion/cp_e09.png',
  './assets/showroom-v5/companion/cp_e10.png',
  './assets/showroom-v5/companion/cp_l01.png',
  './assets/showroom-v5/companion/cp_l02.png',
  './assets/showroom-v5/companion/cp_l03.png',
  './assets/showroom-v5/companion/cp_l04.png',
  './assets/showroom-v5/companion/cp_l05.png',
  './assets/showroom-v5/companion/cp_l06.png',
  './assets/showroom-v5/companion/cp_l07.png',
  './assets/showroom-v5/companion/cp_l08.png',
  './assets/showroom-v5/companion/cp_l09.png',
  './assets/showroom-v5/companion/cp_l10.png',
  './assets/showroom-v10/trophy/tr_a_world_series_constellation.png',
  './assets/showroom-v10/trophy/tr_a_big_ears.png',
  './assets/showroom-v10/trophy/tr_a_world_cup_orb.png',
  './assets/showroom-v10/trophy/tr_a_club_world_orbit.png',
  './assets/showroom-v10/trophy/tr_a_golden_ball.png',
  './assets/showroom-v10/trophy/tr_a_summoners_cup.png',
  './assets/showroom-v10/trophy/tr_a_stanley_tower.png',
  './assets/showroom-v10/trophy/tr_a_golden_gramophone.png',
  './assets/showroom-v10/trophy/tr_a_cinema_guardian.png',
  './assets/showroom-v10/trophy/tr_a_frostmourne_statue.png',
  './assets/showroom-v10/trophy/tr_a_doomhammer_statue.png',
  './assets/showroom-v10/trophy/tr_a_aegis_shield.png',
  ...['ae11_u_champion_stadium','ae11_u_ink_battlefield','ae11_u_navy_bear_victory','ae11_u_twin_night_game','ae11_u_tiger_homerun','ae11_r_eight_formation','ae11_r_red_cliff','ae11_r_crescent_dragon','ae11_r_imperial_jade_seal','ae11_r_moon_archive','ae11_e_storm_dimension','ae11_e_crimson_chaos','ae11_e_starforged_reactor','ae11_e_spider_rift','ae11_e_vibranium_guard','ae11_m_frozen_crown','ae11_m_black_sanctuary','ae11_m_banshee_dirge','ae11_m_iron_warchief','ae11_m_raven_arcane'].flatMap(id=>Array.from({length:8},(_,index)=>`./assets/showroom-v11/ambient_effect/${id}_${String(index+1).padStart(2,'0')}.png`)),
  './assets/showroom-v6/profile_emoji/pe_l_fallen_frost_prince.png',
  './assets/showroom-v6/profile_emoji/pe_l_tideglass_archmage.png',
  './assets/showroom-v6/profile_emoji/pe_l_ironjaw_warchief.png',
  './assets/showroom-v6/profile_emoji/pe_l_raven_tower_guardian.png',
  './assets/showroom-v6/profile_emoji/pe_l_netherblade_betrayer.png',
  './assets/showroom-v6/profile_emoji/pe_l_dark_ranger_queen.png',
  './assets/showroom-v6/profile_emoji/pe_l_worldsoul_stormcaller.png',
  './assets/showroom-v6/profile_emoji/pe_l_felskull_warlock.png',
  './assets/showroom-v6/profile_emoji/pe_l_red_dragon_lifequeen.png',
  './assets/showroom-v6/profile_emoji/pe_l_cataclysm_black_dragon.png',
  './assets/showroom-v8/profile_emoji/pe_u_blue_bear_slugger.webp',
  './assets/showroom-v8/profile_emoji/pe_u_twin_cheer_pair.webp',
  './assets/showroom-v8/profile_emoji/pe_u_soft_bear_fan.webp',
  './assets/showroom-v8/profile_emoji/pe_u_red_tiger_pitcher.webp',
  './assets/showroom-v8/profile_emoji/pe_u_orange_eagle_cheer.webp',
  './assets/showroom-v8/profile_emoji/pe_r_jade_fan_strategist.webp',
  './assets/showroom-v8/profile_emoji/pe_r_crimson_flying_general.webp',
  './assets/showroom-v8/profile_emoji/pe_r_crescent_beard_general.webp',
  './assets/showroom-v8/profile_emoji/pe_r_silver_spear_dragon.webp',
  './assets/showroom-v8/profile_emoji/pe_e_crimson_reactor_sentinel.webp',
  './assets/showroom-v8/profile_emoji/pe_e_storm_prince_guardian.webp',
  './assets/showroom-v8/profile_emoji/pe_e_dimensional_mystic.webp',
  './assets/showroom-v8/profile_emoji/pe_e_crimson_chaos_witch.webp',
  './assets/showroom-v7/emoji_border/eb_u_bear_batter.png',
  './assets/showroom-v7/emoji_border/eb_u_twin_stadium.png',
  './assets/showroom-v7/emoji_border/eb_u_tiger_dugout.png',
  './assets/showroom-v7/emoji_border/eb_u_morning_brew.png',
  './assets/showroom-v7/emoji_border/eb_u_dawn_running.png',
  './assets/showroom-v7/emoji_border/eb_r_wolong_trigram.png',
  './assets/showroom-v7/emoji_border/eb_r_red_hare_armor.png',
  './assets/showroom-v7/emoji_border/eb_r_crescent_dragon.png',
  './assets/showroom-v7/emoji_border/eb_r_imperial_bronze.png',
  './assets/showroom-v7/emoji_border/eb_r_moon_archive.png',
  './assets/showroom-v7/emoji_border/eb_e_crimson_core.png',
  './assets/showroom-v7/emoji_border/eb_e_thunder_guard.png',
  './assets/showroom-v7/emoji_border/eb_e_web_mobility.png',
  './assets/showroom-v7/emoji_border/eb_e_dimensional_sanctum.png',
  './assets/showroom-v7/emoji_border/eb_e_black_vibration.png',
  './assets/showroom-v7/emoji_border/eb_l_frozen_oath.png',
  './assets/showroom-v7/emoji_border/eb_l_nether_twinblade.png',
  './assets/showroom-v7/emoji_border/eb_l_sunwell_bloodcrystal.png',
  './assets/showroom-v7/emoji_border/eb_l_storm_lion_gate.png',
  './assets/showroom-v7/emoji_border/eb_l_rediron_warchief.png',
  './assets/showroom-v8/card_theme/ct8_legendary_frozen_throne.png',
  './assets/showroom-v8/card_theme/ct8_legendary_nether_sanctum.png',
  './assets/showroom-v8/card_theme/panels/frozen_panel_frame.png',
  './assets/showroom-v8/card_theme/panels/nether_panel_frame.png',
  './assets/showroom-v8/card_theme/ct8_u_bear_dugout.webp',
  './assets/showroom-v8/card_theme/ct8_u_twin_stadium.webp',
  './assets/showroom-v8/card_theme/ct8_u_tiger_clubhouse.webp',
  './assets/showroom-v8/card_theme/ct8_u_walnut_cafe.webp',
  './assets/showroom-v8/card_theme/ct8_u_dawn_runner.webp',
  './assets/showroom-v8/card_theme/ct8_r_wolong_silk.webp',
  './assets/showroom-v8/card_theme/ct8_r_red_hare_lacquer.webp',
  './assets/showroom-v8/card_theme/ct8_r_crescent_dragon.webp',
  './assets/showroom-v8/card_theme/ct8_r_imperial_bronze.webp',
  './assets/showroom-v8/card_theme/ct8_r_moon_archive.webp',
  './assets/showroom-v8/card_theme/ct8_e_crimson_reactor.webp',
  './assets/showroom-v8/card_theme/ct8_e_storm_guardian.webp',
  './assets/showroom-v8/card_theme/ct8_e_web_tech.webp',
  './assets/showroom-v8/card_theme/ct8_e_dimensional_mystic.webp',
  './assets/showroom-v8/card_theme/ct8_e_kinetic_alloy.webp',
  './assets/showroom-v8/card_theme/ct8_l_sun_crystal_regalia.webp',
  './assets/showroom-v8/card_theme/ct8_l_raven_arcane.webp',
  './assets/showroom-v8/card_theme/ct8_l_dark_ranger_requiem.webp',
  ...['gs13_e_arc_reactor_hangar','gs13_e_star_shield_command','gs13_u_softbear_ballpark','gs13_u_loopy_twins_party'].map(id=>`./assets/showroom-v13/graph_skin/${id}.webp`),
  ...['ct13_e_crimson_hex_chamber','ct13_e_star_shield_bastion','ct13_u_softbear_dugout','ct13_u_loopy_cheer_lounge'].map(id=>`./assets/showroom-v13/card_theme/${id}.webp`),
  ...['pe13_m_tideborn_queen','pe13_m_sunwell_prince','pe13_e_star_shield_captain','pe13_u_loopy_cheer'].map(id=>`./assets/showroom-v13/profile_emoji/${id}.webp`),
  ...['eb13_m_tide_admiral','eb13_m_banshee_valkyr','eb13_m_raven_timegate','eb13_m_azshara_coral','eb13_e_crimson_hex','eb13_e_star_shield','eb13_u_softbear','eb13_u_loopy'].map(id=>`./assets/showroom-v13/emoji_border/${id}.webp`),
  ...['pm13_m_banshee_arrow','pm13_m_azshara_tiara','pm13_m_sunwell_orb','pm13_e_arc_reactor','pm13_e_crimson_hex','pm13_e_star_shield','pm13_u_loopy_cheer'].flatMap(id=>['high','low'].map(role=>`./assets/showroom-v13/point_marker/${id}_${role}.webp`)),
];
// Install only the application shell. Collection artwork is cached on first
// view by the network-first fetch handler instead of forcing a ~78 MB install.
const CORE_ASSETS=ASSETS.filter(asset=>!asset.startsWith('./assets/'));
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(CORE_ASSETS)));
  self.skipWaiting();
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(keys =>
    Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
  ));
  self.clients.claim();
});

// 네트워크 우선(Network-first): 온라인이면 항상 최신 파일을 받아오고 캐시를 갱신,
// 오프라인일 때만 캐시로 폴백. → 배포 후 Ctrl+Shift+R 없이 자동 반영.
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  // Firebase/Firestore 등 실시간 통신은 서비스워커가 건드리지 않음
  if (url.href.includes('firestore') || url.href.includes('firebase') ||
      url.href.includes('googleapis')) return;

  // 외부 CDN(스크립트 등)은 브라우저 기본 처리에 맡김
  if (url.origin !== location.origin) return;

  e.respondWith(
    fetch(req)
      .then(res => {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
        return res;
      })
      .catch(() => caches.match(req))
  );
});
